### ISSUE TITLE
Where can I find it?

### ISSUE THREAD

**Issue by plaetzchen** [Line-us/Inkscape-Plugin#1]
Added the plugin to the extensions dir that is configured in my Inkscape. What do I have to do to actually interact with the plugin? Can't find it anywhere in the Extensions menu

**Comment by robertpoll** [comment]
I think you need to re-start Inkscape, but other than that it should be there. It's called LUS in the list.

**Comment by plaetzchen** [comment]
OK so I put the folder "lus" into the the directory ~/.config/inkscape/extensions and restarted Inkscape. No it should be a "LUS" entry in the extensions menu?

**Comment by plaetzchen** [comment]
Found it: I needed to put the files into the folder, not the lus folder itself.
